# Generated by Django 4.2.16 on 2024-09-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_options_destination_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image_url',
            new_name='featured_image',
        ),
    ]
