# Generated by Django 4.2.16 on 2024-09-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_packages_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='destination',
            new_name='destination_id',
        ),
    ]
