# Generated by Django 4.2.16 on 2024-09-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_rename_destination_packages_destination_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='destination_id',
            new_name='destination',
        ),
    ]
