# Generated by Django 4.2.16 on 2024-09-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_rename_destination_id_packages_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination'),
        ),
    ]
