# Generated by Django 4.2.16 on 2024-09-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_packages_package_title_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
