# Generated by Django 4.2.16 on 2024-09-22 21:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_alter_packages_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
