# Generated by Django 4.2.16 on 2024-09-23 10:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_packages_featured_image_alter_packages_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='body',
            field=models.TextField(default='Package Body'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='This is the info page')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='destinations.destination')),
            ],
        ),
    ]
