# Generated by Django 4.2.16 on 2024-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0013_alter_packages_body_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='itinerary',
            field=models.TextField(default='Itinerary Detail'),
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
