# Generated by Django 4.2.16 on 2024-09-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_remove_info_content_remove_info_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='id',
        ),
        migrations.AlterField(
            model_name='info',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='info',
            name='localFood',
            field=models.TextField(default='Local Food '),
        ),
        migrations.AlterField(
            model_name='info',
            name='places_to_explore',
            field=models.TextField(default='Place to explore'),
        ),
        migrations.AlterField(
            model_name='info',
            name='things_to_do',
            field=models.TextField(default='Things to do'),
        ),
    ]
