# Generated by Django 4.2.16 on 2024-09-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0021_booking_booking_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='month',
        ),
    ]
