# Generated by Django 4.2.16 on 2024-10-02 23:03

import datetime
import destinations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0022_remove_booking_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_month',
            field=models.DateField(default=datetime.date.today, validators=[destinations.models.Booking.validate_date]),
        ),
    ]
